### ISSUE TITLE
e2e Tests fail

### ISSUE THREAD

**Issue by jasonwilliams** [styled-components/typescript-styled-plugin#9]
Hey @mjbvz it looks like e2e tests now fail since either the TypeScript update or VSCode update.
https://github.com/styled-components/typescript-styled-plugin/actions/runs/4601280928/jobs/8128959986#step:7:12

I reverted both TypeScript and typescript-template-language-service-decorator and it still fails, so it maybe an update in vscode itself.

I don't think this test suite has changed since you last wrote it
Do you know what this could be?

Example of a real request/response using current version
The below is adding `background-color: ` and hitting ctrl + enter with `"typescript.tsserver.log": "verbose"` enabled in the settings.

```
Info 362  [08:34:52.770] request:
    {
      "seq": 85,
      "type": "request",
      "command": "completionEntryDetails",
      "arguments": {
        "file": "/home/jase/workspace/vscode-styled-components/src/tests/suite/colorize-fixtures/attrs.js",
        "line": 5,
        "offset": 20,
        "entryNames": [
          "aliceblue"
        ]
      }
    }
Perf 363  [08:34:52.770] 85::completionEntryDetails: elapsed time (in milliseconds) 0.3259
Info 364  [08:34:52.771] response:
    {"seq":0,"type":"response","command":"completionEntryDetails","request_seq":85,"success":true,"body":[{"name":"aliceblue","kind":"const","kindModifiers":"color","displayParts":[],"documentation":[{"kind":"text","text":"#f0f8ff"}],"tags":[]}]}
```
We can see that its working fine, when ran for real.

However, looking at the e2e test, we see a different story.

<img width="626" alt="failedCompletion" src="https://user-images.githubusercontent.com/936006/229722310-b89366e1-8e8f-435f-93ae-aba3ddb236ea.png">

There's been no changes made to these tests since its been forked, so I guess something upstream has caused these to stop working.

**Comment by Codex-** [comment]
I'm looking into a bug and found that the e2e tests work for me, perhaps worth trying again now?

**Comment by jasonwilliams** [comment]
Yes I fixed it the other day so it’s fine now, this can be closed. Out of interest what big are you looking into?

**Comment by Codex-** [comment]
@jasonwilliams this bug here: https://github.com/styled-components/vscode-styled-components/issues/440

I'll raise an issue here with a failing test case

edit: raised: #21
